white list off

diff --git a/.github/workflows/autotest.yml b/.github/workflows/autotest.yml
--- a/.github/workflows/autotest.yml
+++ b/.github/workflows/autotest.yml
@@ -166,14 +166,14 @@ jobs:
             false
           fi
 
-      - name: Check student ID in whitelist
-        if: steps.cache-dir.outputs.cache-hit != 'true'
-        run: |
-          wget https://raw.githubusercontent.com/OSCPU/ysyx-workbench/whitelist/whitelist.txt
-          if ! grep -o $STUID whitelist.txt 2> /dev/null ; then
-            echo "$STUID is not in whitelist. Abort."
-            false
-          fi
+      # - name: Check student ID in whitelist #白名单
+      #   if: steps.cache-dir.outputs.cache-hit != 'true'
+      #   run: |
+      #     wget https://raw.githubusercontent.com/OSCPU/ysyx-workbench/whitelist/whitelist.txt
+      #     if ! grep -o $STUID whitelist.txt 2> /dev/null ; then
+      #       echo "$STUID is not in whitelist. Abort."
+      #       false
+      #     fi
 
       - name: Parse git log generated by git tracer
         id: tracer
